import type { FundingCall } from './types.js';

export const EU_FUNDING_CALLS: FundingCall[] = [
  {
    identifier: 'HORIZON-EIC-2026-ACCELERATOR-01',
    title: 'EIC Accelerator 2026 — Open',
    deadline: '2026-06-04',
    nextDeadline: '2026-06-04',
    budgetMax: 2500000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: true,
    isMultiStage: true,
    minTrl: 5,
    scope: 'The EIC Accelerator supports individual SMEs, in particular startups and spinoffs, to develop and scale up breakthrough innovations. It covers deep tech and high-tech innovations with high market-creation potential. Grant + equity blended finance available.',
    expectedImpacts: 'Market-creating innovation that creates new industries or disrupts existing ones. Products or services ready for market launch or requiring final development steps. Revenue generation within 3 years post-funding.',
  },
  {
    identifier: 'HORIZON-EIC-2026-PATHFINDEROPEN-01',
    title: 'EIC Pathfinder Open 2026',
    deadline: '2026-09-17',
    nextDeadline: '2026-09-17',
    budgetMax: 3000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 1,
    scope: 'EIC Pathfinder Open supports visionary research for radically new technologies. Projects should address unconventional, high-risk research with a long-term vision for future breakthrough technology. Consortia of at least 3 legal entities from 3 different EU Member States or Associated Countries.',
    expectedImpacts: 'Scientific and technological foundations for a new technology paradigm. Technology roadmap from TRL 1-4 towards eventual market application. New interdisciplinary research community formed around a technology vision.',
  },
  {
    identifier: 'HORIZON-MSCA-2026-PF-01',
    title: 'MSCA Postdoctoral Fellowships 2026',
    deadline: '2026-09-10',
    nextDeadline: '2026-09-10',
    budgetMax: 300000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 1,
    scope: 'MSCA Postdoctoral Fellowships support the career development of researchers with a PhD. Fellows can work in academia, research institutions, or the private sector including SMEs. Projects must have an international mobility component.',
    expectedImpacts: 'Enhanced researcher mobility and career development. Knowledge transfer between sectors and countries. Interdisciplinary collaboration and innovation through researcher placements in non-academic organisations.',
  },
  {
    identifier: 'HORIZON-CL4-2026-RESILIENCE-01',
    title: 'Horizon Europe Cluster 4 — Digital Industry & Space Resilience 2026',
    deadline: '2026-09-03',
    nextDeadline: '2026-09-03',
    budgetMax: 8000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 4,
    scope: 'Supports R&D&I in digital technologies and manufacturing including advanced materials, AI, robotics, photonics, quantum, and micro/nanoelectronics. Projects must address strategic autonomy of European industry in digital technologies.',
    expectedImpacts: 'European leadership in key digital enabling technologies. Strengthened digital industrial base with measurable SME participation. Deployment of next-generation digital solutions in industrial settings.',
  },
  {
    identifier: 'HORIZON-CL5-2026-D3-01',
    title: 'Horizon Europe Cluster 5 — Clean Energy Transition 2026',
    deadline: '2026-09-09',
    nextDeadline: '2026-09-09',
    budgetMax: 6000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 4,
    scope: 'Supports R&D for climate, energy and mobility. Covers renewable energy, energy storage, smart grids, energy efficiency in buildings and industry, carbon capture, and sustainable transport. Contribution to European Green Deal and Clean Industrial Deal.',
    expectedImpacts: 'Accelerated clean energy deployment with demonstrated cost reductions. Cross-border energy systems integration. Measurable CO2 reduction potential from funded technologies.',
  },
  {
    identifier: 'HORIZON-CL6-2026-FARM2FORK-01',
    title: 'Horizon Europe Cluster 6 — Food, Bioeconomy, Natural Resources 2026',
    deadline: '2026-09-03',
    nextDeadline: '2026-09-03',
    budgetMax: 5000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 3,
    scope: 'Supports sustainable food systems, circular bioeconomy, clean water, soil health, and rural communities. Projects must align with Farm to Fork strategy and EU Biodiversity Strategy. Multidisciplinary approaches combining biological, ecological, and social sciences.',
    expectedImpacts: 'More sustainable and resilient food production systems. Reduced environmental footprint of agriculture and food processing. Improved circularity of bio-based materials and resources.',
  },
  {
    identifier: 'HORIZON-CL1-2026-HEALTH-01',
    title: 'Horizon Europe Cluster 1 — Health 2026',
    deadline: '2026-09-23',
    nextDeadline: '2026-09-23',
    budgetMax: 7000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 3,
    scope: 'Supports research on infectious diseases, cancer, rare diseases, mental health, and healthy ageing. Projects must involve clinical validation and patient communities. Focus on personalised medicine, early detection, and innovative therapies.',
    expectedImpacts: 'New diagnostic tools or therapies with defined clinical development pathway. Reduced disease burden with quantified impact metrics. Patient-centric approaches with demonstrated engagement.',
  },
  {
    identifier: 'DIGITAL-2026-AI-09-GENAI-PA',
    title: 'Digital Europe — AI for Public Administration 2026',
    deadline: '2026-06-19',
    nextDeadline: '2026-06-19',
    budgetMax: 4000000,
    eligibleCountries: ['EU'],
    programmeCode: 'DIGITAL',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 6,
    scope: 'Deployment of AI solutions for public administration modernisation. Projects must demonstrate integration with existing government IT infrastructure and compliance with EU AI Act. Pilots in at least 3 EU Member States required.',
    expectedImpacts: 'Measurable efficiency gains in public service delivery. Replicable AI solutions with cross-border potential. Full compliance with EU AI Act and GDPR demonstrated.',
  },
  {
    identifier: 'DIGITAL-2026-CLOUD-01',
    title: 'Digital Europe — European Cloud & Edge Infrastructure 2026',
    deadline: '2026-07-15',
    nextDeadline: '2026-07-15',
    budgetMax: 10000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'DIGITAL',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 7,
    scope: 'Scale-up of federated cloud and edge computing infrastructure aligned with GAIA-X principles. Projects must demonstrate data sovereignty, interoperability, and European data space integration.',
    expectedImpacts: 'Expanded European cloud capacity reducing dependence on non-EU hyperscalers. Operational federated data spaces in at least 2 industry sectors.',
  },
  {
    identifier: 'HORIZON-EIC-2026-TRANSITIONOPEN-01',
    title: 'EIC Transition Open 2026',
    deadline: '2026-10-07',
    nextDeadline: '2026-10-07',
    budgetMax: 2500000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 3,
    scope: 'EIC Transition supports activities that bridge the gap between EIC Pathfinder research and innovation/market deployment. Projects must demonstrate the viability and potential of a new technology and develop a business plan.',
    expectedImpacts: 'Technology validated in relevant environment (TRL 5-6). Initial market validation and first customers identified. Clear spin-off or licensing pathway defined.',
  },
  {
    identifier: 'EUREKA-EUROSTARS-2026',
    title: 'EUREKA Eurostars 2026 — Call for R&D SMEs',
    deadline: '2026-09-11',
    nextDeadline: '2026-09-11',
    budgetMax: 500000,
    eligibleCountries: ['EU', 'EEA', 'EUREKA'],
    programmeCode: 'EUREKA',
    smeOnly: true,
    isMultiStage: false,
    minTrl: 3,
    scope: 'Eurostars supports R&D-performing SMEs to develop innovative products, processes and services for global markets. Projects must be led by an R&D-performing SME and involve at least one partner from another EUREKA country.',
    expectedImpacts: 'New or significantly improved product, process or service ready for commercialisation within 2 years. At least 2 countries participating. Market launch plan with revenue projections.',
  },
  {
    identifier: 'LIFE-2026-CET',
    title: 'LIFE Programme — Clean Energy Transition 2026',
    deadline: '2026-09-18',
    nextDeadline: '2026-09-18',
    budgetMax: 3000000,
    eligibleCountries: ['EU'],
    programmeCode: 'LIFE',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 6,
    scope: 'LIFE CET supports demonstration, deployment and replication of innovative solutions in clean energy. Projects must accelerate the shift towards an energy-efficient, renewable-based economy. Local authorities, SMEs, NGOs, and research organisations can apply.',
    expectedImpacts: 'Quantified energy savings or renewable energy deployment. Replicability in at least 5 EU Member States. Consumer behaviour change measurable at scale.',
  },
  {
    identifier: 'HORIZON-JU-CBE-2026-R-01',
    title: 'CBE JU — Circular Bio-based Europe 2026',
    deadline: '2026-10-21',
    nextDeadline: '2026-10-21',
    budgetMax: 5000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 3,
    scope: 'CBE JU funds research and innovation projects in circular bio-based industries. Projects should develop bio-based materials, chemicals, or fuels from renewable biological resources. Must address value chain development from biomass to end products.',
    expectedImpacts: 'New bio-based value chains commercially viable without subsidies by 2030. Measurable reduction in fossil-based resource use. Industrial-scale demonstration of bio-based processes.',
  },
  {
    identifier: 'HORIZON-JU-CHIPS-2026-KEY-01',
    title: 'Chips JU — Key Digital Technologies 2026',
    deadline: '2026-11-06',
    nextDeadline: '2026-11-06',
    budgetMax: 12000000,
    eligibleCountries: ['EU', 'EEA'],
    programmeCode: 'HORIZON',
    smeOnly: false,
    isMultiStage: false,
    minTrl: 2,
    scope: 'Chips JU supports R&D in semiconductor technology, chip design, and microelectronics manufacturing. Projects must address European strategic autonomy in chips. Collaboration between industry, research, and SMEs required.',
    expectedImpacts: 'European leadership in next-generation chip technology. Reduced dependence on non-EU chip manufacturing. At least 20% SME participation in project consortium.',
  },
  {
    identifier: 'InvestEU-2026-SME-GUARANTEE',
    title: 'InvestEU — SME Window Guarantee Facility 2026',
    deadline: '2026-12-31',
    nextDeadline: '2026-12-31',
    budgetMax: 15000000,
    eligibleCountries: ['EU'],
    programmeCode: 'InvestEU',
    smeOnly: true,
    isMultiStage: false,
    minTrl: 7,
    scope: 'InvestEU SME Window provides guarantee-backed loans and equity investments for SMEs in growth phase. Focuses on innovative SMEs, green transition, and digitalisation. Delivered through national promotional banks and financial intermediaries.',
    expectedImpacts: 'Increased SME investment in innovation and digital transformation. Job creation and economic growth in EU regions. Leverage of at least 5x private capital per euro of EU guarantee.',
  },
];

export function getCallsForProfile(countryOfTaxResidence: string): FundingCall[] {
  const isEU = true; // All EU member states qualify — full list check would be added here
  return EU_FUNDING_CALLS.filter(call => {
    if (call.eligibleCountries.includes('EU') && isEU) return true;
    if (call.eligibleCountries.includes('EEA')) return true;
    if (call.eligibleCountries.includes(countryOfTaxResidence)) return true;
    return false;
  });
}
